[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

board_build.filesystem = spiffs

lib_deps =
  bblanchon/ArduinoJson@^7.3.1
  adafruit/Adafruit SSD1306@^2.5.10
  adafruit/Adafruit GFX Library@^1.11.10
